// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Yrk-AluUI8gJxqShkAVL0FxWKtENPWs',
    appId: '1:52118262744:web:838a1e3f4dba6f60f3d8ad',
    messagingSenderId: '52118262744',
    projectId: 'workinsertion-a2b02',
    authDomain: 'workinsertion-a2b02.firebaseapp.com',
    storageBucket: 'workinsertion-a2b02.appspot.com',
    measurementId: 'G-TK65GJSZ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrN-IM7KCkg_ZeO1NEFqAn0EqB6yP735g',
    appId: '1:52118262744:android:73f703a34feb569cf3d8ad',
    messagingSenderId: '52118262744',
    projectId: 'workinsertion-a2b02',
    storageBucket: 'workinsertion-a2b02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAi17IbSTGpiyBxTKvStuxESAp_GGa060',
    appId: '1:52118262744:ios:528d0a1ccf06c676f3d8ad',
    messagingSenderId: '52118262744',
    projectId: 'workinsertion-a2b02',
    storageBucket: 'workinsertion-a2b02.appspot.com',
    iosBundleId: 'com.example.workInsertion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAi17IbSTGpiyBxTKvStuxESAp_GGa060',
    appId: '1:52118262744:ios:528d0a1ccf06c676f3d8ad',
    messagingSenderId: '52118262744',
    projectId: 'workinsertion-a2b02',
    storageBucket: 'workinsertion-a2b02.appspot.com',
    iosBundleId: 'com.example.workInsertion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Yrk-AluUI8gJxqShkAVL0FxWKtENPWs',
    appId: '1:52118262744:web:cc261ca29824c753f3d8ad',
    messagingSenderId: '52118262744',
    projectId: 'workinsertion-a2b02',
    authDomain: 'workinsertion-a2b02.firebaseapp.com',
    storageBucket: 'workinsertion-a2b02.appspot.com',
    measurementId: 'G-MYZYWMPHND',
  );
}
